In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder , StandardScaler

In [2]:
df = pd.read_csv(r"E:\Learn_ML\Data_sets\titanic.csv")

In [10]:
# print(df)
# df2 = sns.load_dataset("titanic")

In [11]:
# df2

In [12]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [13]:
df.drop(columns=["class" , "deck" , "embark_town" , "alive" , "alone" , "class" , "who" , "adult_male"] , inplace=True)

In [14]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [15]:
X_Train , X_Test , y_Train , y_Test = train_test_split(df.drop(columns=["survived"]) , df["survived"] ,test_size=0.2 , random_state= 42)

In [16]:
X_Train

     pclass     sex   age  sibsp  parch      fare embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [123]:
print(f"X_Test: {X_Test.shape[0]} samples , {X_Test.shape[1]} features")

X_Test: 179 samples , 7 features

Imputation transformer

In [22]:
from sklearn.impute import SimpleImputer

In [23]:
trf1 = ColumnTransformer([
    ("impute_age" , SimpleImputer() , [2]),
    ("impute_embarked", SimpleImputer(strategy = "most_frequent") , [6])] , remainder="passthrough")

In [24]:
trf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

One hot Encoding

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder()

In [42]:
trf2 = ColumnTransformer([
    ("ohe_sex_embarked" , OneHotEncoder(sparse_output=False , handle_unknown="ignore") , [1,6])] ,  remainder = "passthrough")

In [43]:
trf2

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe_sex_embarked',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 [1, 6])])

Scaling

In [44]:
from sklearn.preprocessing import MinMaxScaler

In [57]:
trf3 = ColumnTransformer([
    ("scale" , MinMaxScaler(), slice(0,10))
])

In [58]:
trf3

ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))])

# feature Selection

In [59]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [65]:
trf4 = SelectKBest(score_func = chi2 , k = 8)

In [69]:
print(trf4)

SelectKBest(k=8, score_func=<function chi2 at 0x000001A044BB2FC0>)

train the model

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
trf5 = DecisionTreeClassifier()

In [67]:
# trf5.fit(X_Train, y_Train)

In [73]:
# pipe = Pipeline([
#     ("impute" , trf1),
#     ("ohe" , trf2),
#     ("scale" , trf3),
#     ("feature_selection" , trf4),
#     ("model" , trf5)
# ])

In [75]:
# pipe

In [76]:
from sklearn.pipeline import make_pipeline

In [77]:
pipeline = make_pipeline(trf1 , trf2 , trf3 , trf4 , trf5)

In [85]:
# pipeline

In [ ]:
pipeline.fit(X_Train , y_Train)

Explore Pipeline

In [88]:
from sklearn import set_config
set_config(display="diagram")

In [89]:
pipeline.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'columntransformer-3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=8, score_func=<function chi2 at 0x000001A044BB2FC0>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [94]:
# pipeline.named_steps['trf1'].transformers_[1][1].statistics_
# pipeline.named_steps['trf1'].transformers_[1][1].statistics_

In [95]:
y_pred = pipeline.predict(X_Test)

In [96]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [97]:
from sklearn.metrics import accuracy_score

In [98]:
accuracy_score(y_Test , y_pred)

0.6256983240223464

Cross Validation using Pipeline

In [101]:
from sklearn.model_selection import cross_val_score

cross_val_score(pipeline , X_Train , y_Train , cv=5 , scoring='accuracy').mean()

np.float64(0.6391214419383433)

GridSearch Using pipeline

In [111]:
# pipeline.named_steps
pipeline.get_params().keys()

dict_keys(['memory', 'steps', 'transform_input', 'verbose', 'columntransformer-1', 'columntransformer-2', 'columntransformer-3', 'selectkbest', 'decisiontreeclassifier', 'columntransformer-1__force_int_remainder_cols', 'columntransformer-1__n_jobs', 'columntransformer-1__remainder', 'columntransformer-1__sparse_threshold', 'columntransformer-1__transformer_weights', 'columntransformer-1__transformers', 'columntransformer-1__verbose', 'columntransformer-1__verbose_feature_names_out', 'columntransformer-1__impute_age', 'columntransformer-1__impute_embarked', 'columntransformer-1__impute_age__add_indicator', 'columntransformer-1__impute_age__copy', 'columntransformer-1__impute_age__fill_value', 'columntransformer-1__impute_age__keep_empty_features', 'columntransformer-1__impute_age__missing_values', 'columntransformer-1__impute_age__strategy', 'columntransformer-1__impute_embarked__add_indicator', 'columntransformer-1__impute_embarked__copy', 'columntransformer-1__impute_embarked__fill_value', 'columntransformer-1__impute_embarked__keep_empty_features', 'columntransformer-1__impute_embarked__missing_values', 'columntransformer-1__impute_embarked__strategy', 'columntransformer-2__force_int_remainder_cols', 'columntransformer-2__n_jobs', 'columntransformer-2__remainder', 'columntransformer-2__sparse_threshold', 'columntransformer-2__transformer_weights', 'columntransformer-2__transformers', 'columntransformer-2__verbose', 'columntransformer-2__verbose_feature_names_out', 'columntransformer-2__ohe_sex_embarked', 'columntransformer-2__ohe_sex_embarked__categories', 'columntransformer-2__ohe_sex_embarked__drop', 'columntransformer-2__ohe_sex_embarked__dtype', 'columntransformer-2__ohe_sex_embarked__feature_name_combiner', 'columntransformer-2__ohe_sex_embarked__handle_unknown', 'columntransformer-2__ohe_sex_embarked__max_categories', 'columntransformer-2__ohe_sex_embarked__min_frequency', 'columntransformer-2__ohe_sex_embarked__sparse_output', 'columntransformer-3__force_int_remainder_cols', 'columntransformer-3__n_jobs', 'columntransformer-3__remainder', 'columntransformer-3__sparse_threshold', 'columntransformer-3__transformer_weights', 'columntransformer-3__transformers', 'columntransformer-3__verbose', 'columntransformer-3__verbose_feature_names_out', 'columntransformer-3__scale', 'columntransformer-3__scale__clip', 'columntransformer-3__scale__copy', 'columntransformer-3__scale__feature_range', 'selectkbest__k', 'selectkbest__score_func', 'decisiontreeclassifier__ccp_alpha', 'decisiontreeclassifier__class_weight', 'decisiontreeclassifier__criterion', 'decisiontreeclassifier__max_depth', 'decisiontreeclassifier__max_features', 'decisiontreeclassifier__max_leaf_nodes', 'decisiontreeclassifier__min_impurity_decrease', 'decisiontreeclassifier__min_samples_leaf', 'decisiontreeclassifier__min_samples_split', 'decisiontreeclassifier__min_weight_fraction_leaf', 'decisiontreeclassifier__monotonic_cst', 'decisiontreeclassifier__random_state', 'decisiontreeclassifier__splitter'])

In [113]:
# params = {
#     'trf5__max_depth' : [1,2,3,4,5,None]
# }


params = {
    'decisiontreeclassifier__max_depth':[1,2,3,4,5,None]
}

In [114]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipeline , params , cv=5 , scoring="accuracy")
grid.fit(X_Train , y_Train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer-1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('columntransformer-2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unkno...,
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('columntransformer-3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('selectkbest',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x000001A044BB2FC0>)),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5,
                                                               None]},
             scoring='accuracy')

In [115]:
grid.best_score_

np.float64(0.6391214419383433)

In [116]:
grid.best_params_

{'decisiontreeclassifier__max_depth': 2}

Exporting the pipeline

In [117]:
import pickle
pickle.dump(pipeline , open('pipeline.pickle', 'wb'))

In [ ]:
import pickle
import numpy as np

pipe = pickle.load(open('pipeline.pickle' , 'rb'))

In [124]:
# Assume user input 
test_input = np.array([2, 'male' , 31.0 , 0 , 0 , 10.5 , 'S'],dtype=object).reshape(1,7)

In [122]:
# pipe.predict(test_input)